import assert from 'node:assert/strict';
import {createCheckoutHandler,sendMetaEvent,processMetaBatch} from '../supabase/functions/checkout-api/index';
let calls:any[]=[];
const mockFetch=(status:number,data:any)=>async(url:any,init:any)=>{calls.push({url,init,body:JSON.parse(init.body)});return new Response(JSON.stringify(data),{status});};
const event={event_name:'Purchase',event_id:'purchase_order',event_time:Math.floor(Date.now()/1000),action_source:'website',user_data:{em:['hash']},custom_data:{currency:'BRL',value:49.9}};
assert.equal((await sendMetaEvent('private','v25.0',event,mockFetch(200,{events_received:1}) as any)).ok,true);
assert.equal(calls[0].body.test_event_code,undefined);assert.equal(calls[0].url.includes('private'),false);
assert.equal(calls[0].body.data[0].event_id,'purchase_order');
assert.equal((await sendMetaEvent('private','v25.0',event,mockFetch(200,{events_received:0}) as any)).ok,false);
assert.equal((await sendMetaEvent('private','v25.0',event,mockFetch(429,{}) as any)).retry,true);
assert.equal((await sendMetaEvent('private','v25.0',event,mockFetch(400,{}) as any)).retry,false);
await sendMetaEvent('private','v25.0',event,mockFetch(200,{events_received:1}) as any,'TEST77664');assert.equal(calls.at(-1).body.test_event_code,'TEST77664');
const h=createCheckoutHandler({metaToken:'private',fetchFn:mockFetch(200,{events_received:1}) as any});
assert.equal((await h(new Request('https://example.com/meta/test',{method:'POST'}))).status,401);
assert.equal((await h(new Request('https://example.com/meta/test',{method:'POST',headers:{Authorization:'Bearer private'}}))).status,200);
const finishes:any[]=[];const sb={rpc:async(name:string,args:any)=> name==='meta_claim_batch'?{data:[{event_id:event.event_id,lease_id:'lease',payload:event}]}:(finishes.push(args),{data:true})};
await processMetaBatch(sb,'private','v25.0',mockFetch(500,{}) as any);assert.equal(finishes.at(-1).p_result,'pending');
await processMetaBatch(sb,'private','v25.0',mockFetch(200,{events_received:1}) as any);assert.equal(finishes.at(-1).p_result,'sent');assert.equal(finishes.at(-1).p_event_id,event.event_id);
await processMetaBatch(sb,'private','v25.0',async()=>{throw new Error('timeout');});assert.equal(finishes.at(-1).p_result,'pending');
calls=[];await processMetaBatch({rpc:async()=>({data:[]})},'private','v25.0',mockFetch(200,{events_received:1}) as any);assert.equal(calls.length,0);
console.log('Meta: payload produção/teste, deduplicação, autorização, confirmação HTTP, erros permanentes, 429, 500, timeout e fila vazia: aprovados.');
