import {useEffect,useState} from 'react';
import {LockKeyhole,RefreshCw,LogOut,Users,ShoppingBag,QrCode,Copy,CheckCircle2,ArrowUpRight} from 'lucide-react';
import {panelRequest} from '../lib/storeAnalytics';
export function AdminPanel(){
 const [password,setPassword]=useState(''),[token,setToken]=useState(()=>sessionStorage.getItem('landy_panel')||''),[days,setDays]=useState('30'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function logout(){sessionStorage.removeItem('landy_panel');setToken('');setData(null);}
 async function load(){setBusy(true);setError('');try{setData(await panelRequest('stats?days='+days,undefined,token));}catch(e:any){setError(e.message);if(/sessão|autorizado/i.test(e.message))logout();}finally{setBusy(false);}}
 useEffect(()=>{if(token)void load();},[token,days]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await panelRequest('login',{password});sessionStorage.setItem('landy_panel',r.token);setToken(r.token);setPassword('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const money=(n:number)=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const cards=[['visit','Visitantes',Users,'Navegadores únicos na loja'],['checkout','Chegaram ao checkout',ShoppingBag,'Navegadores únicos no checkout'],['pix','Pix gerados',QrCode,'Pedidos com código Pix emitido'],['copy','Copiaram o Pix',Copy,'Pedidos com ao menos uma cópia'],['paid','Pagamentos confirmados',CheckCircle2,'Confirmação recebida no servidor']] as const;
 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900 px-4 py-8 sm:px-8"><div className="max-w-6xl mx-auto">
 <header className="flex items-center justify-between gap-4 mb-8"><div><p className="text-xs uppercase tracking-[.2em] text-primary font-bold">Landy Shaner · Área privada</p><h1 className="text-3xl font-display font-bold mt-2">Visão da loja</h1></div>{token&&<button onClick={logout} className="flex gap-2 text-sm items-center"><LogOut size={16}/> Sair</button>}</header>
 {!token?<form onSubmit={login} className="max-w-sm mx-auto mt-16 rounded-3xl bg-white border border-slate-200 p-8 shadow-sm"><LockKeyhole className="text-primary mb-5" size={32}/><h2 className="text-xl font-bold">Acessar painel</h2><p className="text-sm text-slate-500 mt-2">Informe a senha de administração.</p><label htmlFor="panel-password" className="block text-sm font-bold mt-6 mb-2">Senha</label><input id="panel-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required className="w-full border rounded-xl p-3"/><button disabled={busy} className="cta-grad text-white w-full rounded-xl p-3 font-bold mt-4">{busy?'Entrando…':'Entrar'}</button>{error&&<p role="alert" className="text-sm text-red-600 mt-3">{error}</p>}</form>:<>
 <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><label className="text-sm font-semibold">Período <select aria-label="Período" value={days} onChange={e=>setDays(e.target.value)} className="bg-white border rounded-xl p-3 ml-3"><option value="1">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="0">Todo o período</option></select></label><button disabled={busy} onClick={load} className="flex items-center gap-2 bg-white border rounded-xl px-4 py-3 text-sm"><RefreshCw size={16} className={busy?'animate-spin':''}/> Atualizar</button></div>
 {error&&<p role="alert" className="rounded-xl bg-red-50 text-red-700 p-4 mb-4">{error}</p>}
 <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{cards.map(([key,label,Icon,detail])=><section key={key} className="bg-white border border-slate-200 rounded-2xl p-5"><Icon size={22} className="text-primary mb-5"/><p className="text-sm font-semibold min-h-10">{label}</p><p className="font-display text-3xl font-bold my-3">{data?data[key]:'—'}</p><p className="text-xs text-slate-500 leading-relaxed">{detail}</p></section>)}</div>
 <div className="grid sm:grid-cols-2 gap-4 mt-5"><section className="bg-slate-900 text-white rounded-2xl p-6"><p className="text-sm text-slate-300">Receita confirmada no período</p><p className="text-3xl font-display font-bold mt-3">{data?money(data.revenue):'—'}</p></section><section className="bg-white border rounded-2xl p-6"><p className="text-sm text-slate-500 flex gap-2 items-center"><ArrowUpRight size={18}/> Pix que viraram pagamento</p><p className="text-3xl font-display font-bold mt-3">{data?.pix?((data.paid/data.pix)*100).toFixed(1)+'%':'—'}</p></section></div>
 <section className="bg-white border rounded-2xl mt-6 overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Pedidos recentes</h2><p className="text-xs text-slate-500 mt-1">Até 50 pedidos do período, sem dados pessoais do comprador.</p></div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-slate-50 text-slate-500"><tr>{['Pedido','Criado em','Total','Situação'].map(x=><th key={x} className="p-4 font-medium">{x}</th>)}</tr></thead><tbody>{data?.orders?.map((o:any)=><tr key={o.order_id} className="border-t"><td className="p-4 font-mono text-xs break-all">{o.order_id}</td><td className="p-4 whitespace-nowrap">{new Date(o.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</td><td className="p-4 whitespace-nowrap">{money(o.total_price)}</td><td className="p-4"><span className={o.status==='paid'?'text-emerald-700 font-bold':'text-slate-500'}>{({paid:'Pago',pending:'Aguardando Pix',creating:'Em processamento',uncertain:'Em verificação',canceled:'Cancelado',refunded:'Reembolsado',charged_back:'Estornado'} as Record<string,string>)[o.status]||o.status}</span></td></tr>)}{data&&!data.orders?.length&&<tr><td colSpan={4} className="p-8 text-center text-slate-500">Nenhum pedido neste período.</td></tr>}</tbody></table></div></section>
 <p className="text-xs text-slate-500 leading-relaxed mt-5">Visitas são navegadores únicos; recarregar a página não aumenta o total. As visitas e cópias começam a ser medidas a partir desta atualização. Pix e pagamentos incluem os pedidos anteriores. Bloqueadores, navegadores diferentes e limpeza de armazenamento podem afetar a contagem de visitantes. Datas no horário de Brasília.</p>
 </> }</div></main>;
}

